#List of the top-level eDSL rules to check
SPEC_NAMES:=fn-execute-success fn-execute-failure
KEVM_REPO_DIR:=/home/sbugrara/evm-semantics-call-log/
VERIFICATION_NUM:=0
TMPLS:=../resources/module-tmpl.k ../resources/spec-tmpl-call-log.k

include ../resources/kprove.mak