apiVersion: batch/v1
kind: Job
metadata:
  name: kworker-job
spec:
  parallelism: 18
  template:
    metadata:
      name: kworker-job
    spec:
      containers:
        - name: c
          image: 626351541105.dkr.ecr.us-east-2.amazonaws.com/kworker:latest
          resources:
            requests:
              memory: "12G"
            limits:
              memory: "12G"
      restartPolicy: OnFailure